echo y | pip uninstall MVSCoursePythonKids_ru -q
echo y | pip uninstall CoursePythonAdult_ru -q
echo y | pip uninstall wds_files_general -q
echo y | pip uninstall wds_files_CoursePythonAdult_1 -q
echo y | pip uninstall wrap_data_source -q
echo y | pip uninstall wrap_mENdRU -q
echo y | pip uninstall wrap_py -q
echo y | pip uninstall thread_signals -q
echo y | pip uninstall wrap_engine -q